version: '3.8'

services:
#  nginx:
#    container_name: nginx
#    build:
#      context: requirements/nginx/
#      dockerfile: Dockerfile
#    ports:
#      - "443:443"
#    environment:
#      - .env
#    volumes:
#      - wordpress_vol:/var/www/wordpress
#    networks:
#      - inception
#    restart: always
#    depends_on:
#      - wordpress
#      - mariadb

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    expose:
      - "9000"
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/wordpress
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    expose:
      - "3306"
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/josh/Documents/volumes/mariadb'
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/josh/Documents/volumes/wordpress'