mysql -e "CREATE DATABASE IF NO EXISTS \`${SQL_DATABASE}\`;"
mysql -e "CREATE USER IF NO EXISTS \`${SQL_USER}\`@`localhost` IDENTIFIED BY \`${SQL_USER_PWD}\`;"
mysql -e "GRANT ALL PRIVILEGES ON \`${SQL_DATABASE}\`.*"